apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  source:
    targetRevision: release
  plugin:
    env:
    - name: ENVIRONMENT
      value: production
  syncPolicy:
    automated:
      selfHeal: true
