repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com

environments:
  develop:
  production:

releases:
  - name: sealed-secrets
    namespace: kube-system
    chart: stable/sealed-secrets
