apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: argocd
  namespace: argocd
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: argocd-server
      port: 80
  virtualhost:
    fqdn: argocd.akichan.tokyo
    tls:
      secretName: argocd-akichan-tokyo-prod-tls
