configs:
  secret:
    argocdServerAdminPasswordMtime: "2006-01-02T15:04:05Z"

server:
  extraArgs:
  - --insecure
  certificate:
    domain: argocd.akichan.tokyo
  config:
    configManagementPlugins: |
      - name: helmfile
        generate:
          command: ["helmfile"]
          args: ["template"]

repoServer:
  volumes:
  - name: custom-tools
    emptyDir: {}
  volumeMounts:
  - name: custom-tools
    mountPath: /usr/local/bin/helmfile
    subPath: helmfile
  initContainers:
  - name: download-tools
    image: alpine:3.12
    command: [sh, -c]
    args:
    - wget -qO /custom-tools/helmfile https://github.com/roboll/helmfile/releases/download/v0.125.7/helmfile_linux_amd64 &&
      chmod +x /custom-tools/helmfile
    volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools

