configs:
  secret:
    argocdServerAdminPasswordMtime: "2006-01-02T15:04:05Z"

server:
  extraArgs:
  - --insecure
  certificate:
    domain: argocd.akichan.tokyo
  config:
    configManagementPlugins: |
      - name: helmfile
        init:
          command: ["argo-cd-helmfile.sh"]
          args: ["init"]
        generate:
          command: ["argo-cd-helmfile.sh"]
          args: ["generate"]

repoServer:
  volumes:
  - name: custom-tools
    emptyDir: {}
  volumeMounts:
    - mountPath: /usr/local/bin/argo-cd-helmfile.sh
      name: custom-tools
      subPath: argo-cd-helmfile.sh
    - mountPath: /usr/local/bin/helmfile
      name: custom-tools
      subPath: helmfile
  initContainers:
  - name: download-tools
    image: alpine:3.12
    command: [sh, -c]
    args:
    - wget -qO /custom-tools/argo-cd-helmfile.sh https://raw.githubusercontent.com/ch1aki/argo-cd-helmfile/master/src/argo-cd-helmfile.sh &&
      chmod +x /custom-tools/argo-cd-helmfile.sh &&
      wget -qO /custom-tools/helmfile https://github.com/roboll/helmfile/releases/download/v0.125.7/helmfile_linux_amd64 &&
      chmod +x /custom-tools/helmfile
    volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools

