apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-apikey-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgCo8SSUPEdi71XWYto9Qri0+rZlfGA//Lzayj7Uga3kn8WVqGDVa50nf8uvdSMrJEJ/6S+x7Mpad3GQm5VVVPOgqE4dCYXowv5nPZlXlWsOP2eH3Tne1ewewdt3eRDxVX+BLTNb59xTRWGw55+YsBrnE9j3trLo8Yx4lk85X/wcU5efWNp+h5KYHZN6oKkIZI7B45xVRM+biugqY6V1qtBhXoh3JH4+0Om7ABWb28GubWNvi2O0BNIEMkorxpuNzTo5yCS37C/n2oymOMAcZTRHRW8IHM/r4jL6uT1/3ziwKul16Po+W3S36pcfaXP9L68tX35VPCJSd7GlJMHZ921MbszY2ys3u+y4HA0hXQM5zEY4hFltuNbtGOkdQgh1K8o7mxnSNkN6aEupZqN1IGqsXQFpsQJ71B9NMg1x4vFqMTTzI6gt3j3pqKlNvC0bymw3J3GBMRArtxDiWjhsY+/Ok9OqbZDm6CBKr5WUKjiO3h+F2YUR89cfnPUzQzNLZWOCEnTi4I1gWc2omidQWcsi3chUWUXdlTM37fi0q8NSSeKuJMoX7vEN7ZN4Jp+QJbNknhn7RmpGYAE7seP80GbmtR/GcbeoYwqS4uCRiWqd3gq2nv+4BMgGjx88gFtukuXK9C8sU9FC8y8MO14m02Lb/gvxfxj/m+/aY88/HMaTLeJsp4zVlX/J86DkgtxQ+AqdPRlQUPA92ekeUO6y852SuB6Ux0vYfzzjchet8TZWXQTpXalw
  template:
    metadata:
      name: cloudflare-apikey-secret
      namespace: cert-manager
    type: Opaque

