repositories:
- name: jetstack
  url: https://charts.jetstack.io

environments:
  develop:
  production:

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.1.0

